-- Sections/BlackTemple.lua  --  spatial wing layout for the Automarker wing switcher
local _, L3F = ...

L3F:RegisterSections({
    raid  = "Black Temple",
    mapID = 564,                                  -- Black Temple (instanceMapID)
    sections = {
        { name = "Path to Naj'entus", npcs = {
            { id = 22884, name = "Leviathan" },
            { id = 22877, name = "Coilskar Wrangler" },
            { id = 22878, name = "Aqueous Lord" },
            { id = 22881, name = "Aqueous Surger" },
            { id = 22883, name = "Aqueous Spawn" },
            { id = 22875, name = "Coilskar Sea-Caller" },
            { id = 22873, name = "Coilskar General" },
            { id = 22876, name = "Coilskar Soothsayer" },
            { id = 22874, name = "Coilskar Harpooner" },
            { id = 22885, name = "Dragon Turtle" },
            { id = 22887, name = "High Warlord Naj'entus" },
        }},
        { name = "Path to Supremus", npcs = {
            { id = 22883, name = "Aqueous Spawn" },               -- also in Path to Naj'entus
            { id = 23028, name = "Bonechewer Taskmaster" },
            { id = 22963, name = "Bonechewer Worker" },
            { id = 22954, name = "Illidari Fearbringer" },
            { id = 22960, name = "Dragonmaw Wyrmcaller" },
            { id = 23030, name = "Dragonmaw Sky Stalker" },
            { id = 23330, name = "Dragonmaw Wind Reaver" },
            { id = 22898, name = "Supremus" },
        }},
        { name = "Path to Shade of Akama", npcs = {
            { id = 22853, name = "Illidari Defiler" },
            { id = 23337, name = "Illidari Centurion" },
            { id = 22869, name = "Illidari Boneslicer" },
            { id = 23339, name = "Illidari Heartseeker" },
            { id = 22855, name = "Illidari Nightlord" },
            { id = 22844, name = "Ashtongue Battlelord" },
            { id = 22849, name = "Ashtongue Feral Spirit" },
            { id = 22845, name = "Ashtongue Mystic" },
            { id = 22847, name = "Ashtongue Primalist" },
            { id = 22846, name = "Ashtongue Stormcaller" },
            { id = 23374, name = "Ashtongue Stalker" },
            { id = 23318, name = "Ashtongue Rogue" },
            { id = 23215, name = "Ashtongue Sorcerer" },
            { id = 23524, name = "Ashtongue Spiritbinder" },
            { id = 23523, name = "Ashtongue Elementalist" },
            { id = 23216, name = "Ashtongue Defender" },
            { id = 23319, name = "Ashtongue Broken" },
            { id = 22848, name = "Storm Fury" },
            { id = 23389, name = "Fallen Ally" },
            { id = 23421, name = "Ashtongue Channeler" },
            { id = 22841, name = "Shade of Akama" },
        }},
        { name = "Path to Teron Gorefiend", npcs = {
            { id = 22880, name = "Shadowmoon Champion" },
            { id = 23018, name = "Shadowmoon Houndmaster" },
            { id = 22946, name = "Shadowmoon War Hound" },
            { id = 23083, name = "Shadowmoon Riding Hound" },
            { id = 22879, name = "Shadowmoon Reaver" },
            { id = 22945, name = "Shadowmoon Blood Mage" },
            { id = 23371, name = "Shadowmoon Fallen" },
            { id = 23047, name = "Shadowmoon Soldier" },
            { id = 23147, name = "Shadowmoon Grunt" },
            { id = 23049, name = "Shadowmoon Weapon Master" },
            { id = 22882, name = "Shadowmoon Deathshaper" },
            { id = 22953, name = "Wrathbone Flayer" },
            { id = 23172, name = "Hand of Gorefiend" },
            { id = 22871, name = "Teron Gorefiend" },
        }},
        { name = "Path to Gurtogg/Reliquary", npcs = {
            { id = 23196, name = "Bonechewer Behemoth" },
            { id = 23235, name = "Bonechewer Blade Fury" },
            { id = 23237, name = "Bonechewer Blood Prophet" },
            { id = 23222, name = "Bonechewer Brawler" },
            { id = 23239, name = "Bonechewer Combatant" },
            { id = 23236, name = "Bonechewer Shield Disciple" },
            { id = 23223, name = "Bonechewer Spectator" },
            { id = 23232, name = "Mutant War Hound" },
            { id = 23399, name = "Suffering Soul Fragment" },
            { id = 23398, name = "Angered Soul Fragment" },
            { id = 23401, name = "Hungering Soul Fragment" },
            { id = 23418, name = "Essence of Suffering" },
            { id = 23469, name = "Enslaved Soul" },
            { id = 23419, name = "Essence of Desire" },
            { id = 23420, name = "Essence of Anger" },
            { id = 22948, name = "Gurtogg Bloodboil" },
        }},
        { name = "Path to Shahraz", npcs = {
            { id = 22853, name = "Illidari Defiler" },            -- also in Path to Shade of Akama
            { id = 23337, name = "Illidari Centurion" },          -- also in Path to Shade of Akama
            { id = 22869, name = "Illidari Boneslicer" },         -- also in Path to Shade of Akama
            { id = 23339, name = "Illidari Heartseeker" },        -- also in Path to Shade of Akama
            { id = 22965, name = "Devoted Steward" },
            { id = 22939, name = "Temple Acolyte" },
            { id = 22955, name = "Charming Patron" },
            { id = 22959, name = "Ardent Host" },
            { id = 22956, name = "Priestess of Torment" },
            { id = 22964, name = "Priestess of Delight" },
            { id = 22962, name = "Mistress of Woe" },
            { id = 22957, name = "Mistress of Dementia" },
            { id = 23436, name = "Image of Dementia" },
            { id = 22947, name = "Mother Shahraz" },
        }},
        { name = "Path to Illidari Council", npcs = {
            { id = 23394, name = "Promenade Sentinel" },
            { id = 23403, name = "Illidari Assassin" },
            { id = 23402, name = "Illidari Battle-mage" },
            { id = 23400, name = "Illidari Archon" },
            { id = 23397, name = "Illidari Blood Lord" },
            { id = 22950, name = "High Nethermancer Zerevor" },
            { id = 22952, name = "Veras Darkshadow" },
            { id = 22949, name = "Gathios the Shatterer" },
            { id = 22951, name = "Lady Malande" },
        }},
        { name = "Illidan fight", npcs = {
            { id = 22917, name = "Illidan Stormrage" },
            { id = 22997, name = "Flame of Azzinoth" },
            { id = 23375, name = "Shadow Demon" },
            { id = 23498, name = "Parasitic Shadowfiend" },
            { id = 22929, name = "Greater Shadowfiend" },
        }},
    },
})
