-- Sections/SerpentshrineCavern.lua  --  spatial wing layout for the Automarker wing switcher
local _, L3F = ...

L3F:RegisterSections({
    raid  = "Serpentshrine Cavern",
    mapID = 548,                                  -- Serpentshrine Cavern (instanceMapID)
    sections = {
        { name = "Entrance to Hydross", npcs = {
            { id = 21246, name = "Serpentshrine Sporebat" },
            { id = 21221, name = "Coilfang Beast-Tamer" },
            { id = 21339, name = "Coilfang Hate-Screamer" },
            { id = 21251, name = "Underbog Colossus" },
            { id = 22352, name = "Colossus Rager" },
            { id = 22347, name = "Colossus Lurker" },
            { id = 21260, name = "Purified Water Elemental" },
            { id = 21253, name = "Tainted Water Elemental" },
            { id = 21216, name = "Hydross the Unstable" },
            { id = 22036, name = "Tainted Spawn of Hydross" },
            { id = 22035, name = "Pure Spawn of Hydross" },
        }},
        { name = "Path to Lurker", npcs = {
            { id = 21220, name = "Coilfang Priestess" },
            { id = 21301, name = "Coilfang Shatterer" },
            { id = 21263, name = "Greyheart Technician" },
            { id = 21218, name = "Vashj'ir Honor Guard" },
            { id = 21217, name = "The Lurker Below" },
            { id = 21873, name = "Coilfang Guardian" },
            { id = 21865, name = "Coilfang Ambusher" },
        }},
        { name = "Crossroads", npcs = {
            { id = 21229, name = "Greyheart Tidecaller" },
            { id = 22236, name = "Water Elemental Totem" },
            { id = 21298, name = "Coilfang Serpentguard" },
            { id = 21232, name = "Greyheart Skulker" },
            { id = 21230, name = "Greyheart Nether-Mage" },
            { id = 21251, name = "Underbog Colossus" },
        }},
        { name = "Path to Leotheras", npcs = {
            { id = 21299, name = "Coilfang Fathom-Witch" },
            { id = 21298, name = "Coilfang Serpentguard" },
            { id = 21230, name = "Greyheart Nether-Mage" },
            { id = 21232, name = "Greyheart Skulker" },
            { id = 21229, name = "Greyheart Tidecaller" },
            { id = 22236, name = "Water Elemental Totem" },
            { id = 21863, name = "Serpentshrine Lurker" },
            { id = 21231, name = "Greyheart Shield-Bearer" },
            { id = 21806, name = "Greyheart Spellbinder" },
            { id = 21215, name = "Leotheras the Blind" },
            { id = 21875, name = "Shadow of Leotheras" },
        }},
        { name = "Path to Karathress", npcs = {
            { id = 21229, name = "Greyheart Tidecaller" },
            { id = 22236, name = "Water Elemental Totem" },
            { id = 21231, name = "Greyheart Shield-Bearer" },
            { id = 21251, name = "Underbog Colossus" },
            { id = 22352, name = "Colossus Rager" },
            { id = 22347, name = "Colossus Lurker" },
            { id = 21214, name = "Fathom-Lord Karathress" },
            { id = 21965, name = "Fathom-Guard Tidalvess" },
            { id = 21964, name = "Fathom-Guard Caribdis" },
            { id = 21966, name = "Fathom-Guard Sharkkis" },
            { id = 22119, name = "Fathom Lurker" },
            { id = 22120, name = "Fathom Sporebat" },
        }},
        { name = "Path to Morogrim", npcs = {
            { id = 21299, name = "Coilfang Fathom-Witch" },
            { id = 21298, name = "Coilfang Serpentguard" },
            { id = 21301, name = "Coilfang Shatterer" },
            { id = 21226, name = "Tidewalker Shaman" },
            { id = 21228, name = "Tidewalker Hydromancer" },
            { id = 21225, name = "Tidewalker Warrior" },
            { id = 21224, name = "Tidewalker Depth-Seer" },
            { id = 21227, name = "Tidewalker Harpooner" },
            { id = 21213, name = "Morogrim Tidewalker" },
            { id = 21920, name = "Tidewalker Lurker" },
        }},
        { name = "Path to Vashj", npcs = {
            { id = 21299, name = "Coilfang Fathom-Witch" },
            { id = 21298, name = "Coilfang Serpentguard" },
            { id = 21229, name = "Greyheart Tidecaller" },
            { id = 22236, name = "Water Elemental Totem" },
            { id = 21232, name = "Greyheart Skulker" },
            { id = 21230, name = "Greyheart Nether-Mage" },
            { id = 21251, name = "Underbog Colossus" },
            { id = 21212, name = "Lady Vashj" },
            { id = 22055, name = "Coilfang Elite" },
            { id = 22056, name = "Coilfang Strider" },
            { id = 22009, name = "Tainted Elemental" },
        }},
    },
})
