-- L3FTools - Data/RaidPlannerCatalog
-- Auto-generated by _migration/raid_planner/build_catalog_lua.py.
-- Drives the Raid Planner tab's encounter + background dropdowns.
-- To regenerate: run convert_images.py then build_catalog_lua.py.

local _, L3F = ...

L3F.raidPlannerCatalog = {
    {
        raid = "Sunwell Plateau",
        encounters = {
            {
                name = "Kalecgos",
                backgrounds = {
                    { label = "Arena", slug = "kalecgos-arena" },
                },
            },
            {
                name = "Brutallus",
                backgrounds = {
                    { label = "Full arena", slug = "brutallus-full-arena" },
                    { label = "Zoomed", slug = "brutallus-zoomed" },
                },
            },
            {
                name = "Felmyst",
                backgrounds = {
                    { label = "Full arena", slug = "felmyst-full-arena" },
                    { label = "Zoomed", slug = "felmyst-zoomed" },
                },
            },
            {
                name = "The Eredar Twins",
                backgrounds = {
                    { label = "Arena", slug = "the-eredar-twins-arena" },
                    { label = "Zoomed out", slug = "the-eredar-twins-zoomed-out" },
                },
            },
            {
                name = "M'uru",
                backgrounds = {
                    { label = "Arena", slug = "muru-arena" },
                    { label = "Reversed", slug = "muru-reversed" },
                },
            },
            {
                name = "Kil'jaeden",
                backgrounds = {
                    { label = "Alternate", slug = "kiljeaden-alternate" },
                    { label = "Arena", slug = "kiljeaden-arena" },
                },
            },
        },
    },
    {
        raid = "Black Temple",
        encounters = {
            {
                name = "High Warlord Naj'entus",
                backgrounds = {
                    { label = "Angled", slug = "high-warlord-najentus-angled" },
                    { label = "Side", slug = "high-warlord-najentus-side" },
                },
            },
            {
                name = "Supremus",
                backgrounds = {
                    { label = "Angled", slug = "supremus-angled" },
                    { label = "Top-down", slug = "supremus-top-down" },
                },
            },
            {
                name = "Shade of Akama",
                backgrounds = {
                    { label = "Corner", slug = "shade-of-akama-corner" },
                    { label = "Full room", slug = "shade-of-akama-full-room" },
                    { label = "Top-down", slug = "shade-of-akama-top-down" },
                },
            },
            {
                name = "Teron Gorefiend",
                backgrounds = {
                    { label = "Full room", slug = "teron-gorefiend-full-room" },
                    { label = "Platform", slug = "teron-gorefiend-platform" },
                    { label = "Side room", slug = "teron-gorefiend-side-room" },
                },
            },
            {
                name = "Gurtogg Bloodboil",
                backgrounds = {
                    { label = "Alternate", slug = "gurtogg-bloodboil-alternate" },
                    { label = "Full room", slug = "gurtogg-bloodboil-full-room" },
                },
            },
            {
                name = "Reliquary of Souls",
                backgrounds = {
                    { label = "Full room", slug = "reliquary-of-souls-full-room" },
                },
            },
            {
                name = "Mother Shahraz",
                backgrounds = {
                    { label = "Alternate", slug = "mother-shahraz-alternate" },
                    { label = "Fish fountain", slug = "mother-shahraz-fish-fountain" },
                    { label = "Main", slug = "mother-shahraz-main" },
                },
            },
            {
                name = "The Illidari Council",
                backgrounds = {
                    { label = "Full room", slug = "the-illidari-council-full-room" },
                    { label = "Platform", slug = "the-illidari-council-platform" },
                },
            },
            {
                name = "Illidan Stormrage",
                backgrounds = {
                    { label = "Full room", slug = "illidan-stormrage-full-room" },
                    { label = "Pillars (reversed)", slug = "illidan-stormrage-pillars-reversed" },
                    { label = "Pillars", slug = "illidan-stormrage-pillars" },
                },
            },
        },
    },
    {
        raid = "Battle for Mount Hyjal",
        encounters = {
            {
                name = "Alliance Village",
                backgrounds = {
                    { label = "Default", slug = "alliance-village" },
                },
            },
            {
                name = "Horde Village",
                backgrounds = {
                    { label = "Default", slug = "horde-village" },
                },
            },
            {
                name = "Archimonde",
                backgrounds = {
                    { label = "Default", slug = "archimonde" },
                },
            },
        },
    },
    {
        raid = "Serpentshrine Cavern",
        encounters = {
            {
                name = "Hydross the Unstable",
                backgrounds = {
                    { label = "Main", slug = "hydross-the-unstable-main" },
                },
            },
            {
                name = "The Lurker Below",
                backgrounds = {
                    { label = "Overhead", slug = "the-lurker-below-overhead" },
                    { label = "Side", slug = "the-lurker-below-side" },
                },
            },
            {
                name = "Leotheras the Blind",
                backgrounds = {
                    { label = "Alternate", slug = "leotheras-the-blind-alternate" },
                    { label = "Overhead", slug = "leotheras-the-blind-overhead" },
                },
            },
            {
                name = "Fathom-Lord Karathress",
                backgrounds = {
                    { label = "Alternate", slug = "fathom-lord-karathress-alternate" },
                    { label = "Overhead", slug = "fathom-lord-karathress-overhead" },
                    { label = "Side", slug = "fathom-lord-karathress-side" },
                },
            },
            {
                name = "Morogrim Tidewalker",
                backgrounds = {
                    { label = "Alternate", slug = "morogrim-tidewalker-alternate" },
                    { label = "Overhead", slug = "morogrim-tidewalker-overhead" },
                },
            },
            {
                name = "Lady Vashj",
                backgrounds = {
                    { label = "Alternate", slug = "lady-vashj-alternate" },
                    { label = "Overhead", slug = "lady-vashj-overhead" },
                },
            },
        },
    },
    {
        raid = "The Eye: Tempest Keep",
        encounters = {
            {
                name = "Al'ar",
                backgrounds = {
                    { label = "Overhead", slug = "alar-overhead" },
                    { label = "Side", slug = "alar-side" },
                },
            },
            {
                name = "Void Reaver",
                backgrounds = {
                    { label = "Alternate", slug = "void-reaver-alternate" },
                    { label = "Entrance", slug = "void-reaver-entrance" },
                },
            },
            {
                name = "High Astromancer Solarian",
                backgrounds = {
                    { label = "Alternate", slug = "high-astromancer-solarian-alternate" },
                    { label = "Main", slug = "high-astromancer-solarian-main" },
                },
            },
            {
                name = "Kael'thas Sunstrider",
                backgrounds = {
                    { label = "Alternate", slug = "kaelthas-sunstrider-alternate" },
                    { label = "Main", slug = "kaelthas-sunstrider-main" },
                },
            },
        },
    },
    {
        raid = "Karazhan",
        encounters = {
            {
                name = "Attumen the Huntsman",
                backgrounds = {
                    { label = "Default", slug = "attumen-the-huntsman" },
                },
            },
            {
                name = "Moroes",
                backgrounds = {
                    { label = "Default", slug = "moroes" },
                },
            },
            {
                name = "Opera Event",
                backgrounds = {
                    { label = "Default", slug = "opera-event" },
                },
            },
            {
                name = "Maiden of Virtue",
                backgrounds = {
                    { label = "Default", slug = "maiden-of-virtue" },
                },
            },
            {
                name = "The Curator",
                backgrounds = {
                    { label = "Doorway", slug = "the-curator-doorway" },
                    { label = "Hallway", slug = "the-curator-hallway" },
                },
            },
            {
                name = "Chess Event",
                backgrounds = {
                    { label = "Default", slug = "chess-event" },
                },
            },
            {
                name = "Terestian Illhoof",
                backgrounds = {
                    { label = "Default", slug = "terestian-illhoof" },
                },
            },
            {
                name = "Shade of Aran",
                backgrounds = {
                    { label = "Default", slug = "shade-of-aran" },
                },
            },
            {
                name = "Netherspite",
                backgrounds = {
                    { label = "Default", slug = "netherspite" },
                },
            },
            {
                name = "Nightbane",
                backgrounds = {
                    { label = "Close-up", slug = "nightbane-close-up" },
                    { label = "Overhead", slug = "nightbane-overhead" },
                },
            },
            {
                name = "Prince Malchezaar",
                backgrounds = {
                    { label = "Default", slug = "prince-malchezaar" },
                },
            },
        },
    },
    {
        raid = "Gruul's Lair",
        encounters = {
            {
                name = "High King Maulgar",
                backgrounds = {
                    { label = "Original", slug = "high-king-maulgar-original" },
                    { label = "Wide", slug = "high-king-maulgar-wide" },
                },
            },
            {
                name = "Gruul the Dragonkiller",
                backgrounds = {
                    { label = "Door", slug = "gruul-the-dragonkiller-door" },
                    { label = "Room", slug = "gruul-the-dragonkiller-room" },
                    { label = "Wide", slug = "gruul-the-dragonkiller-wide" },
                },
            },
        },
    },
    {
        raid = "Magtheridon's Lair",
        encounters = {
            {
                name = "Magtheridon",
                backgrounds = {
                    { label = "Original", slug = "magtheridon-original" },
                    { label = "Wide", slug = "magtheridon-wide" },
                },
            },
        },
    },
}
